-- Verify {{catalog}}.ontology.kg_nodes / kg_edges agree with the TBox in
-- src/ontology/exec_analyst.ttl. src/ontology/test_generate.py checks the MODEL;
-- this checks the DATA that the model produced. Job param {{catalog}} expands
-- to a quoted string (e.g. 'gold_dev').
-- GENERATED by src/ontology/generate.py from src/ontology/exec_analyst.ttl - do not edit by hand.
--
-- Checks:
--   1. No orphan edges — every subject/object must resolve to a kg_nodes row.
--   2. No duplicate (node_type, node_key) — that pair is the graph's primary key.
--   3. Every rel is one the TTL declares.
--   4. Every edge's (subject_type, object_type) matches that rel's declared
--      rdfs:domain / rdfs:range.
--   5. No declared entity class or relation materialized to zero rows — a silently
--      empty union is the failure mode a row-count-blind check would miss.

-- --- Diagnostic (run ad hoc in the SQL editor; 0 rows = pass) ---

EXECUTE IMMEDIATE
"SELECT check_name, detail FROM (
  SELECT 'orphan_edge_subject' AS check_name,
    concat_ws(' ', e.rel, e.subject_type, e.subject_key) AS detail
  FROM " || {{catalog}} || ".ontology.kg_edges e
  LEFT JOIN " || {{catalog}} || ".ontology.kg_nodes n
    ON n.node_type = e.subject_type AND n.node_key = e.subject_key
  WHERE n.node_key IS NULL

  UNION ALL
  SELECT 'orphan_edge_object',
    concat_ws(' ', e.rel, e.object_type, e.object_key)
  FROM " || {{catalog}} || ".ontology.kg_edges e
  LEFT JOIN " || {{catalog}} || ".ontology.kg_nodes n
    ON n.node_type = e.object_type AND n.node_key = e.object_key
  WHERE n.node_key IS NULL

  UNION ALL
  SELECT 'duplicate_node', concat_ws(' ', node_type, node_key)
  FROM " || {{catalog}} || ".ontology.kg_nodes
  GROUP BY node_type, node_key HAVING COUNT(*) > 1

  UNION ALL
  SELECT 'unknown_rel', rel
  FROM " || {{catalog}} || ".ontology.kg_edges
  WHERE rel NOT IN ('campaignRunsOnChannel', 'campaignTargetsSegment', 'dealerSellsModel', 'lineProducesModel', 'partStockedAt', 'plantHasLine', 'plantProducesModel', 'supplierSuppliesPart')
  GROUP BY rel

  UNION ALL
  SELECT 'unknown_node_type', node_type
  FROM " || {{catalog}} || ".ontology.kg_nodes
  WHERE node_type NOT IN ('CalendarDate', 'CampaignChannel', 'CustomerSegment', 'Dealer', 'MarketingCampaign', 'Part', 'Plant', 'ProductionLine', 'Supplier', 'VehicleModel', 'Warehouse')
  GROUP BY node_type

  UNION ALL
  SELECT 'domain_range_violation',
    concat_ws(' ', e.rel, ':', e.subject_type, '->', e.object_type)
  FROM " || {{catalog}} || ".ontology.kg_edges e
  WHERE (e.rel = 'campaignRunsOnChannel' AND (e.subject_type <> 'MarketingCampaign' OR e.object_type <> 'CampaignChannel')) OR (e.rel = 'campaignTargetsSegment' AND (e.subject_type <> 'MarketingCampaign' OR e.object_type <> 'CustomerSegment')) OR (e.rel = 'dealerSellsModel' AND (e.subject_type <> 'Dealer' OR e.object_type <> 'VehicleModel')) OR (e.rel = 'lineProducesModel' AND (e.subject_type <> 'ProductionLine' OR e.object_type <> 'VehicleModel')) OR (e.rel = 'partStockedAt' AND (e.subject_type <> 'Part' OR e.object_type <> 'Warehouse')) OR (e.rel = 'plantHasLine' AND (e.subject_type <> 'Plant' OR e.object_type <> 'ProductionLine')) OR (e.rel = 'plantProducesModel' AND (e.subject_type <> 'Plant' OR e.object_type <> 'VehicleModel')) OR (e.rel = 'supplierSuppliesPart' AND (e.subject_type <> 'Supplier' OR e.object_type <> 'Part'))
  GROUP BY e.rel, e.subject_type, e.object_type

  UNION ALL
  SELECT 'empty_node_type', t.node_type
  FROM (SELECT explode(array('CalendarDate', 'CampaignChannel', 'CustomerSegment', 'Dealer', 'MarketingCampaign', 'Part', 'Plant', 'ProductionLine', 'Supplier', 'VehicleModel', 'Warehouse')) AS node_type) t
  LEFT JOIN " || {{catalog}} || ".ontology.kg_nodes n ON n.node_type = t.node_type
  GROUP BY t.node_type HAVING COUNT(n.node_key) = 0

  UNION ALL
  SELECT 'empty_rel', r.rel
  FROM (SELECT explode(array('campaignRunsOnChannel', 'campaignTargetsSegment', 'dealerSellsModel', 'lineProducesModel', 'partStockedAt', 'plantHasLine', 'plantProducesModel', 'supplierSuppliesPart')) AS rel) r
  LEFT JOIN " || {{catalog}} || ".ontology.kg_edges e ON e.rel = r.rel
  GROUP BY r.rel HAVING COUNT(e.rel) = 0
) ORDER BY check_name, detail";

-- --- Assertion (job task; raise_error fails the run) ---

EXECUTE IMMEDIATE
"WITH violations AS (
  SELECT 'orphan_edge_subject' AS check_name
  FROM " || {{catalog}} || ".ontology.kg_edges e
  LEFT JOIN " || {{catalog}} || ".ontology.kg_nodes n
    ON n.node_type = e.subject_type AND n.node_key = e.subject_key
  WHERE n.node_key IS NULL

  UNION ALL
  SELECT 'orphan_edge_object'
  FROM " || {{catalog}} || ".ontology.kg_edges e
  LEFT JOIN " || {{catalog}} || ".ontology.kg_nodes n
    ON n.node_type = e.object_type AND n.node_key = e.object_key
  WHERE n.node_key IS NULL

  UNION ALL
  SELECT 'duplicate_node'
  FROM " || {{catalog}} || ".ontology.kg_nodes
  GROUP BY node_type, node_key HAVING COUNT(*) > 1

  UNION ALL
  SELECT 'unknown_rel'
  FROM " || {{catalog}} || ".ontology.kg_edges
  WHERE rel NOT IN ('campaignRunsOnChannel', 'campaignTargetsSegment', 'dealerSellsModel', 'lineProducesModel', 'partStockedAt', 'plantHasLine', 'plantProducesModel', 'supplierSuppliesPart')

  UNION ALL
  SELECT 'unknown_node_type'
  FROM " || {{catalog}} || ".ontology.kg_nodes
  WHERE node_type NOT IN ('CalendarDate', 'CampaignChannel', 'CustomerSegment', 'Dealer', 'MarketingCampaign', 'Part', 'Plant', 'ProductionLine', 'Supplier', 'VehicleModel', 'Warehouse')

  UNION ALL
  SELECT 'domain_range_violation'
  FROM " || {{catalog}} || ".ontology.kg_edges e
  WHERE (e.rel = 'campaignRunsOnChannel' AND (e.subject_type <> 'MarketingCampaign' OR e.object_type <> 'CampaignChannel')) OR (e.rel = 'campaignTargetsSegment' AND (e.subject_type <> 'MarketingCampaign' OR e.object_type <> 'CustomerSegment')) OR (e.rel = 'dealerSellsModel' AND (e.subject_type <> 'Dealer' OR e.object_type <> 'VehicleModel')) OR (e.rel = 'lineProducesModel' AND (e.subject_type <> 'ProductionLine' OR e.object_type <> 'VehicleModel')) OR (e.rel = 'partStockedAt' AND (e.subject_type <> 'Part' OR e.object_type <> 'Warehouse')) OR (e.rel = 'plantHasLine' AND (e.subject_type <> 'Plant' OR e.object_type <> 'ProductionLine')) OR (e.rel = 'plantProducesModel' AND (e.subject_type <> 'Plant' OR e.object_type <> 'VehicleModel')) OR (e.rel = 'supplierSuppliesPart' AND (e.subject_type <> 'Supplier' OR e.object_type <> 'Part'))

  UNION ALL
  SELECT 'empty_node_type'
  FROM (SELECT explode(array('CalendarDate', 'CampaignChannel', 'CustomerSegment', 'Dealer', 'MarketingCampaign', 'Part', 'Plant', 'ProductionLine', 'Supplier', 'VehicleModel', 'Warehouse')) AS node_type) t
  LEFT JOIN " || {{catalog}} || ".ontology.kg_nodes n ON n.node_type = t.node_type
  GROUP BY t.node_type HAVING COUNT(n.node_key) = 0

  UNION ALL
  SELECT 'empty_rel'
  FROM (SELECT explode(array('campaignRunsOnChannel', 'campaignTargetsSegment', 'dealerSellsModel', 'lineProducesModel', 'partStockedAt', 'plantHasLine', 'plantProducesModel', 'supplierSuppliesPart')) AS rel) r
  LEFT JOIN " || {{catalog}} || ".ontology.kg_edges e ON e.rel = r.rel
  GROUP BY r.rel HAVING COUNT(e.rel) = 0
)
SELECT CASE WHEN COUNT(*) = 0
  THEN 'PASS: kg_nodes/kg_edges match the TBox (11 classes, 8 relations)'
  ELSE raise_error(concat('FAIL: knowledge-graph integrity violated: ', concat_ws(', ', collect_set(check_name))))
END AS result
FROM violations";
