-- Tag the Executive Analyst metric views + linked dim tables for ontology wiring.
-- Job param {{catalog}} expands to a quoted string (e.g. 'gold_dev'); concatenate into DDL.
-- GENERATED by src/ontology/generate.py from src/ontology/exec_analyst.ttl - do not edit by hand.

-- --- Metric views ---

EXECUTE IMMEDIATE
"ALTER VIEW " || {{catalog}} || ".manufacturing_analytics.metrics_production_execution SET TAGS (
  'domain' = 'manufacturing',
  'grain' = 'production_row',
  'kpi' = 'true',
  'glossary_source' = 'src/ontology/exec_analyst.ttl',
  'glossary_terms' = 'Downtime,OEE,Plant,ProductionLine'
)";

EXECUTE IMMEDIATE
"ALTER VIEW " || {{catalog}} || ".marketing_analytics.metrics_campaign_performance SET TAGS (
  'domain' = 'marketing',
  'grain' = 'campaign_flight',
  'kpi' = 'true',
  'glossary_source' = 'src/ontology/exec_analyst.ttl',
  'glossary_terms' = 'CampaignSpend,Conversion,CostPerLead,ROAS,CampaignChannel,CustomerSegment,MarketingCampaign'
)";

EXECUTE IMMEDIATE
"ALTER VIEW " || {{catalog}} || ".revenue_analytics.metrics_sales_order SET TAGS (
  'domain' = 'revenue',
  'grain' = 'order',
  'kpi' = 'true',
  'glossary_source' = 'src/ontology/exec_analyst.ttl',
  'glossary_terms' = 'Bookings,DeliveredOrderRevenue,Discount,DiscountPercent,Revenue,Dealer,VehicleModel'
)";

EXECUTE IMMEDIATE
"ALTER VIEW " || {{catalog}} || ".supply_chain_analytics.metrics_inventory_snapshot SET TAGS (
  'domain' = 'inventory',
  'grain' = 'snapshot',
  'kpi' = 'true',
  'glossary_source' = 'src/ontology/exec_analyst.ttl',
  'glossary_terms' = 'DaysOfSupply,InventoryTurnover,StockValuation,Part,Warehouse'
)";

EXECUTE IMMEDIATE
"ALTER VIEW " || {{catalog}} || ".supply_chain_analytics.metrics_supplier_quality SET TAGS (
  'domain' = 'supplier_quality',
  'grain' = 'inspection',
  'kpi' = 'true',
  'glossary_source' = 'src/ontology/exec_analyst.ttl',
  'glossary_terms' = 'COPQ,PPM,QualityScore,Supplier'
)";

-- --- Dim tables (entity bindings) ---

EXECUTE IMMEDIATE
"ALTER TABLE " || {{catalog}} || ".dim.dim_campaign SET TAGS (
  'glossary_source' = 'src/ontology/exec_analyst.ttl',
  'glossary_terms' = 'MarketingCampaign'
)";

EXECUTE IMMEDIATE
"ALTER TABLE " || {{catalog}} || ".dim.dim_channel SET TAGS (
  'glossary_source' = 'src/ontology/exec_analyst.ttl',
  'glossary_terms' = 'CampaignChannel'
)";

EXECUTE IMMEDIATE
"ALTER TABLE " || {{catalog}} || ".dim.dim_customer_segment SET TAGS (
  'glossary_source' = 'src/ontology/exec_analyst.ttl',
  'glossary_terms' = 'CustomerSegment'
)";

EXECUTE IMMEDIATE
"ALTER TABLE " || {{catalog}} || ".dim.dim_date SET TAGS (
  'glossary_source' = 'src/ontology/exec_analyst.ttl',
  'glossary_terms' = 'CalendarDate'
)";

EXECUTE IMMEDIATE
"ALTER TABLE " || {{catalog}} || ".dim.dim_dealer SET TAGS (
  'glossary_source' = 'src/ontology/exec_analyst.ttl',
  'glossary_terms' = 'Dealer'
)";

EXECUTE IMMEDIATE
"ALTER TABLE " || {{catalog}} || ".dim.dim_part SET TAGS (
  'glossary_source' = 'src/ontology/exec_analyst.ttl',
  'glossary_terms' = 'Part'
)";

EXECUTE IMMEDIATE
"ALTER TABLE " || {{catalog}} || ".dim.dim_plant SET TAGS (
  'glossary_source' = 'src/ontology/exec_analyst.ttl',
  'glossary_terms' = 'Plant'
)";

EXECUTE IMMEDIATE
"ALTER TABLE " || {{catalog}} || ".dim.dim_production_line SET TAGS (
  'glossary_source' = 'src/ontology/exec_analyst.ttl',
  'glossary_terms' = 'ProductionLine'
)";

EXECUTE IMMEDIATE
"ALTER TABLE " || {{catalog}} || ".dim.dim_supplier SET TAGS (
  'glossary_source' = 'src/ontology/exec_analyst.ttl',
  'glossary_terms' = 'Supplier'
)";

EXECUTE IMMEDIATE
"ALTER TABLE " || {{catalog}} || ".dim.dim_vehicle_model SET TAGS (
  'glossary_source' = 'src/ontology/exec_analyst.ttl',
  'glossary_terms' = 'VehicleModel'
)";

EXECUTE IMMEDIATE
"ALTER TABLE " || {{catalog}} || ".dim.dim_warehouse SET TAGS (
  'glossary_source' = 'src/ontology/exec_analyst.ttl',
  'glossary_terms' = 'Warehouse'
)";
