-- Tag the five Executive Analyst metric views + linked dim tables for ontology wiring.
-- Job param {{catalog}} expands to a quoted string (e.g. 'gold_dev'); concatenate into DDL.
-- Tags: domain, grain, kpi, glossary_source, glossary_terms (from src/ontology/glossary.yml links_to).
-- GENERATED by src/ontology/generate_tag_sql.py - do not edit by hand; regenerate after glossary changes.

-- --- Metric views ---

EXECUTE IMMEDIATE
"ALTER VIEW " || {{catalog}} || ".revenue_analytics.metrics_sales_order SET TAGS (
  'domain' = 'revenue',
  'grain' = 'order',
  'kpi' = 'true',
  'glossary_source' = 'src/ontology/glossary.yml',
  'glossary_terms' = 'revenue,bookings,discount,discount_percent,delivered_order,dealer,model'
)";

EXECUTE IMMEDIATE
"ALTER VIEW " || {{catalog}} || ".marketing_analytics.metrics_campaign_performance SET TAGS (
  'domain' = 'marketing',
  'grain' = 'campaign_flight',
  'kpi' = 'true',
  'glossary_source' = 'src/ontology/glossary.yml',
  'glossary_terms' = 'roas,cpl,conversion_marketing,campaign,channel,segment'
)";

EXECUTE IMMEDIATE
"ALTER VIEW " || {{catalog}} || ".manufacturing_analytics.metrics_production_execution SET TAGS (
  'domain' = 'manufacturing',
  'grain' = 'production_row',
  'kpi' = 'true',
  'glossary_source' = 'src/ontology/glossary.yml',
  'glossary_terms' = 'oee,downtime,plant,production_line,model'
)";

EXECUTE IMMEDIATE
"ALTER VIEW " || {{catalog}} || ".supply_chain_analytics.metrics_inventory_snapshot SET TAGS (
  'domain' = 'inventory',
  'grain' = 'snapshot',
  'kpi' = 'true',
  'glossary_source' = 'src/ontology/glossary.yml',
  'glossary_terms' = 'stockout_risk,days_of_supply,inventory_turnover,part,warehouse'
)";

EXECUTE IMMEDIATE
"ALTER VIEW " || {{catalog}} || ".supply_chain_analytics.metrics_supplier_quality SET TAGS (
  'domain' = 'supplier_quality',
  'grain' = 'inspection',
  'kpi' = 'true',
  'glossary_source' = 'src/ontology/glossary.yml',
  'glossary_terms' = 'ppm,copq,part,supplier'
)";

-- --- Dim tables (entity links_to) ---

EXECUTE IMMEDIATE
"ALTER TABLE " || {{catalog}} || ".dim.dim_plant SET TAGS (
  'glossary_source' = 'src/ontology/glossary.yml',
  'glossary_terms' = 'plant'
)";

EXECUTE IMMEDIATE
"ALTER TABLE " || {{catalog}} || ".dim.dim_production_line SET TAGS (
  'glossary_source' = 'src/ontology/glossary.yml',
  'glossary_terms' = 'production_line'
)";

EXECUTE IMMEDIATE
"ALTER TABLE " || {{catalog}} || ".dim.dim_part SET TAGS (
  'glossary_source' = 'src/ontology/glossary.yml',
  'glossary_terms' = 'part'
)";

EXECUTE IMMEDIATE
"ALTER TABLE " || {{catalog}} || ".dim.dim_warehouse SET TAGS (
  'glossary_source' = 'src/ontology/glossary.yml',
  'glossary_terms' = 'warehouse'
)";

EXECUTE IMMEDIATE
"ALTER TABLE " || {{catalog}} || ".dim.dim_supplier SET TAGS (
  'glossary_source' = 'src/ontology/glossary.yml',
  'glossary_terms' = 'supplier'
)";

EXECUTE IMMEDIATE
"ALTER TABLE " || {{catalog}} || ".dim.dim_dealer SET TAGS (
  'glossary_source' = 'src/ontology/glossary.yml',
  'glossary_terms' = 'dealer'
)";

EXECUTE IMMEDIATE
"ALTER TABLE " || {{catalog}} || ".dim.dim_vehicle_model SET TAGS (
  'glossary_source' = 'src/ontology/glossary.yml',
  'glossary_terms' = 'model'
)";

EXECUTE IMMEDIATE
"ALTER TABLE " || {{catalog}} || ".dim.dim_campaign SET TAGS (
  'glossary_source' = 'src/ontology/glossary.yml',
  'glossary_terms' = 'campaign'
)";

EXECUTE IMMEDIATE
"ALTER TABLE " || {{catalog}} || ".dim.dim_channel SET TAGS (
  'glossary_source' = 'src/ontology/glossary.yml',
  'glossary_terms' = 'channel'
)";

EXECUTE IMMEDIATE
"ALTER TABLE " || {{catalog}} || ".dim.dim_customer_segment SET TAGS (
  'glossary_source' = 'src/ontology/glossary.yml',
  'glossary_terms' = 'segment'
)";
