#!/usr/bin/env python3
"""Regenerate tag_metric_views.sql from glossary.yml links_to.

Prevents glossary_terms tags from drifting away from the Git glossary.
Domain / grain / kpi stay in VIEW_META below (not in glossary.yml).

Usage (from repo root):
  python src/ontology/generate_tag_sql.py
  python src/ontology/generate_tag_sql.py --check   # exit 1 if SQL is stale
"""

from __future__ import annotations

import argparse
import sys
from collections import OrderedDict
from pathlib import Path

try:
    import yaml
except ImportError as e:  # pragma: no cover
    raise SystemExit("PyYAML is required: pip install pyyaml") from e

REPO_ROOT = Path(__file__).resolve().parents[2]
GLOSSARY_PATH = REPO_ROOT / "src" / "ontology" / "glossary.yml"
OUT_PATH = REPO_ROOT / "src" / "metric_views" / "tag_metric_views.sql"
GLOSSARY_SOURCE = "src/ontology/glossary.yml"

# Stable view order + governance tags (Step 1 skipped UC Domains → domain tag).
VIEW_META: OrderedDict[str, dict[str, str]] = OrderedDict(
    [
        (
            "revenue_analytics.metrics_sales_order",
            {"domain": "revenue", "grain": "order"},
        ),
        (
            "marketing_analytics.metrics_campaign_performance",
            {"domain": "marketing", "grain": "campaign_flight"},
        ),
        (
            "manufacturing_analytics.metrics_production_execution",
            {"domain": "manufacturing", "grain": "production_row"},
        ),
        (
            "supply_chain_analytics.metrics_inventory_snapshot",
            {"domain": "inventory", "grain": "snapshot"},
        ),
        (
            "supply_chain_analytics.metrics_supplier_quality",
            {"domain": "supplier_quality", "grain": "inspection"},
        ),
    ]
)


def load_glossary(path: Path) -> list[dict]:
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    terms = data.get("terms") or []
    if not isinstance(terms, list):
        raise SystemExit(f"Invalid glossary: expected terms list in {path}")
    return terms


def collect_links(terms: list[dict]) -> tuple[dict[str, list[str]], dict[str, list[str]]]:
    """Map view FQN → term ids and table FQN → term ids (glossary order)."""
    view_terms: dict[str, list[str]] = {v: [] for v in VIEW_META}
    table_terms: OrderedDict[str, list[str]] = OrderedDict()

    for term in terms:
        tid = term.get("id")
        if not tid:
            continue
        for link in term.get("links_to") or []:
            if not isinstance(link, dict):
                continue
            view = link.get("view")
            table = link.get("table")
            if view:
                if view not in view_terms:
                    raise SystemExit(
                        f"Term {tid!r} links to unknown view {view!r}. "
                        f"Add it to VIEW_META in generate_tag_sql.py."
                    )
                if tid not in view_terms[view]:
                    view_terms[view].append(tid)
            if table:
                if table not in table_terms:
                    table_terms[table] = []
                if tid not in table_terms[table]:
                    table_terms[table].append(tid)

    for view, ids in view_terms.items():
        if not ids:
            raise SystemExit(f"No glossary terms link to view {view!r}")

    return view_terms, dict(table_terms)


def _terms_csv(ids: list[str]) -> str:
    return ",".join(ids)


def render_sql(view_terms: dict[str, list[str]], table_terms: dict[str, list[str]]) -> str:
    lines: list[str] = [
        "-- Tag the five Executive Analyst metric views + linked dim tables for ontology wiring.",
        "-- Job param {{catalog}} expands to a quoted string (e.g. 'gold_dev'); concatenate into DDL.",
        "-- Tags: domain, grain, kpi, glossary_source, glossary_terms (from src/ontology/glossary.yml links_to).",
        "-- GENERATED by src/ontology/generate_tag_sql.py - do not edit by hand; regenerate after glossary changes.",
        "",
        "-- --- Metric views ---",
        "",
    ]

    for view, meta in VIEW_META.items():
        terms = _terms_csv(view_terms[view])
        lines.append("EXECUTE IMMEDIATE")
        lines.append(
            f'"ALTER VIEW " || {{{{catalog}}}} || ".{view} SET TAGS (\n'
            f"  'domain' = '{meta['domain']}',\n"
            f"  'grain' = '{meta['grain']}',\n"
            f"  'kpi' = 'true',\n"
            f"  'glossary_source' = '{GLOSSARY_SOURCE}',\n"
            f"  'glossary_terms' = '{terms}'\n"
            f')";'
        )
        lines.append("")

    lines.append("-- --- Dim tables (entity links_to) ---")
    lines.append("")

    for table, ids in table_terms.items():
        terms = _terms_csv(ids)
        lines.append("EXECUTE IMMEDIATE")
        lines.append(
            f'"ALTER TABLE " || {{{{catalog}}}} || ".{table} SET TAGS (\n'
            f"  'glossary_source' = '{GLOSSARY_SOURCE}',\n"
            f"  'glossary_terms' = '{terms}'\n"
            f')";'
        )
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if tag_metric_views.sql does not match glossary.yml",
    )
    args = parser.parse_args()

    terms = load_glossary(GLOSSARY_PATH)
    view_terms, table_terms = collect_links(terms)
    sql = render_sql(view_terms, table_terms)

    if args.check:
        if not OUT_PATH.is_file():
            print(f"MISSING {OUT_PATH}", file=sys.stderr)
            return 1
        current = OUT_PATH.read_text(encoding="utf-8")
        if current != sql:
            print(
                f"STALE {OUT_PATH.relative_to(REPO_ROOT)} — run: "
                f"python src/ontology/generate_tag_sql.py",
                file=sys.stderr,
            )
            return 1
        print(f"OK {OUT_PATH.relative_to(REPO_ROOT)} matches glossary.yml")
        return 0

    OUT_PATH.write_text(sql, encoding="utf-8", newline="\n")
    print(f"Wrote {OUT_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
