#!/usr/bin/env python3
"""Generate exec_analyst.ttl (OWL TBox) from glossary.yml + graph.yml.

YAML remains the system of record. Do not hand-edit the Turtle file.
Protégé may open the .ttl for review only — never save over it.

Usage (from repo root):
  python src/ontology/generate_owl.py
  python src/ontology/generate_owl.py --check   # exit 1 if Turtle is stale
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError as e:  # pragma: no cover
    raise SystemExit("PyYAML is required: pip install -r src/ontology/requirements.txt") from e

try:
    from rdflib import OWL, RDF, RDFS, SKOS, Graph, Literal, Namespace, URIRef
    from rdflib.namespace import XSD
except ImportError as e:  # pragma: no cover
    raise SystemExit(
        "rdflib is required: pip install -r src/ontology/requirements.txt"
    ) from e

# owlready2 is the planned OWL toolkit; Turtle is emitted via rdflib for
# deterministic, byte-comparable serialization (--check).
try:
    import owlready2  # noqa: F401
except ImportError as e:  # pragma: no cover
    raise SystemExit(
        "owlready2 is required: pip install -r src/ontology/requirements.txt"
    ) from e

REPO_ROOT = Path(__file__).resolve().parents[2]
GLOSSARY_PATH = REPO_ROOT / "src" / "ontology" / "glossary.yml"
GRAPH_PATH = REPO_ROOT / "src" / "ontology" / "graph.yml"
OUT_PATH = REPO_ROOT / "src" / "ontology" / "exec_analyst.ttl"

BASE_IRI = "https://focaloid.com/ontology/executive-analyst#"
EA = Namespace(BASE_IRI)

# Ontology document IRI (without trailing fragment for owl:Ontology).
ONTOLOGY_IRI = "https://focaloid.com/ontology/executive-analyst"

HEADER_COMMENT = """\
# GENERATED by src/ontology/generate_owl.py — do not edit by hand.
# Source: src/ontology/glossary.yml + src/ontology/graph.yml
# Regenerate: python src/ontology/generate_owl.py
#            (or ./deploy.sh regen-tags)
#
"""


def id_to_fragment(term_id: str) -> str:
    """Convert glossary id to PascalCase IRI fragment (delivered_order → DeliveredOrder)."""
    parts = re.split(r"[_\s-]+", term_id.strip())
    if not parts or not parts[0]:
        raise SystemExit(f"Invalid term id: {term_id!r}")
    return "".join(p[:1].upper() + p[1:] for p in parts if p)


def prop_uri(prop_id: str) -> URIRef:
    """Object-property id → camelCase IRI (has_line → hasLine)."""
    parts = re.split(r"[_\s-]+", prop_id.strip())
    if not parts or not parts[0]:
        raise SystemExit(f"Invalid object property id: {prop_id!r}")
    first = parts[0].lower()
    rest = "".join(p[:1].upper() + p[1:].lower() for p in parts[1:] if p)
    return EA[first + rest]


def term_uri(term_id: str) -> URIRef:
    return EA[id_to_fragment(term_id)]


def load_glossary(path: Path) -> list[dict]:
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    terms = data.get("terms") or []
    if not isinstance(terms, list):
        raise SystemExit(f"Invalid glossary: expected terms list in {path}")
    return terms


def load_object_properties(path: Path) -> list[dict]:
    if not path.is_file():
        return []
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    props = data.get("object_properties") or []
    if not isinstance(props, list):
        raise SystemExit(f"Invalid graph.yml: expected object_properties list in {path}")
    return props


def validate_terms(terms: list[dict]) -> dict[str, dict]:
    by_id: dict[str, dict] = {}
    for term in terms:
        tid = term.get("id")
        if not tid:
            raise SystemExit("Glossary term missing id")
        if tid in by_id:
            raise SystemExit(f"Duplicate glossary id: {tid!r}")
        by_id[tid] = term

    for term in terms:
        tid = term["id"]
        for field in ("related", "not_same_as"):
            for ref in term.get(field) or []:
                if ref not in by_id:
                    raise SystemExit(
                        f"Term {tid!r} {field} references unknown id {ref!r}"
                    )
    return by_id


def validate_object_properties(
    props: list[dict], term_ids: set[str]
) -> list[dict]:
    seen: set[str] = set()
    seen_rel: set[str] = set()
    for prop in props:
        pid = prop.get("id")
        if not pid:
            raise SystemExit("object_properties entry missing id")
        if pid in seen:
            raise SystemExit(f"Duplicate object property id: {pid!r}")
        seen.add(pid)

        rel = prop.get("rel")
        if not rel:
            raise SystemExit(f"Object property {pid!r} missing rel")
        if rel in seen_rel:
            raise SystemExit(f"Duplicate object property rel: {rel!r}")
        seen_rel.add(rel)

        domain = prop.get("domain")
        range_ = prop.get("range")
        if not domain or not range_:
            raise SystemExit(f"Object property {pid!r} needs domain and range")
        if domain not in term_ids:
            raise SystemExit(
                f"Object property {pid!r} domain {domain!r} not in glossary"
            )
        if range_ not in term_ids:
            raise SystemExit(
                f"Object property {pid!r} range {range_!r} not in glossary"
            )
    return props


def classify_term(term: dict) -> str:
    """Return parent class local name: Entity | AmbiguousTerm | Measure."""
    links = term.get("links_to") or []
    if not links:
        return "AmbiguousTerm"
    for link in links:
        if isinstance(link, dict) and link.get("table"):
            return "Entity"
    return "Measure"


def link_annotations(link: dict) -> list[tuple[URIRef, str]]:
    """Map one links_to entry to (annotation_property, catalog-relative string)."""
    out: list[tuple[URIRef, str]] = []
    view = link.get("view")
    table = link.get("table")
    measure = link.get("measure")
    field = link.get("field")

    if table:
        out.append((EA.realizedByTable, str(table)))
    if view and measure:
        out.append((EA.realizedByMeasure, f"{view}.{measure}"))
    elif view and field:
        out.append((EA.realizedByField, f"{view}.{field}"))
    elif view:
        out.append((EA.realizedByView, str(view)))
    elif measure and not view:
        raise SystemExit(f"links_to measure without view: {link!r}")
    elif field and not view and not table:
        raise SystemExit(f"links_to field without view: {link!r}")
    return out


def collapse_ws(text: str) -> str:
    return re.sub(r"\s+", " ", (text or "").strip())


def add_object_properties(g: Graph, props: list[dict]) -> None:
    """Emit owl:ObjectProperty with rdfs:domain / rdfs:range (TBox only)."""
    for prop in sorted(props, key=lambda p: str(p.get("id") or "")):
        uri = prop_uri(prop["id"])
        g.add((uri, RDF.type, OWL.ObjectProperty))
        rel = prop.get("rel") or prop["id"]
        g.add((uri, RDFS.label, Literal(str(rel))))
        comment = collapse_ws(prop.get("comment") or "")
        if comment:
            g.add((uri, RDFS.comment, Literal(comment, lang="en")))
        g.add((uri, RDFS.domain, term_uri(prop["domain"])))
        g.add((uri, RDFS.range, term_uri(prop["range"])))


def build_graph(terms: list[dict], object_properties: list[dict] | None = None) -> Graph:
    by_id = validate_terms(terms)
    props = validate_object_properties(
        object_properties or [], set(by_id.keys())
    )
    g = Graph()
    g.bind("ea", EA)
    g.bind("owl", OWL)
    g.bind("rdfs", RDFS)
    g.bind("skos", SKOS)
    g.bind("rdf", RDF)
    g.bind("xsd", XSD)

    ontology = URIRef(ONTOLOGY_IRI)
    g.add((ontology, RDF.type, OWL.Ontology))
    g.add(
        (
            ontology,
            RDFS.comment,
            Literal(
                "Executive Analyst OWL TBox generated from glossary.yml and graph.yml. "
                "KPI math lives in Unity Catalog metric views; this file is meaning only. "
                "Instance graph is ontology.kg_nodes / kg_edges in Unity Catalog.",
                lang="en",
            ),
        )
    )

    # Annotation properties
    for local, comment in (
        ("ownedBy", "Glossary owner (finance, marketing, …)"),
        ("realizedByView", "Catalog-relative metric view path"),
        ("realizedByMeasure", "Catalog-relative view.measure path"),
        ("realizedByField", "Catalog-relative view.field path"),
        ("realizedByTable", "Catalog-relative dim table path"),
    ):
        prop = EA[local]
        g.add((prop, RDF.type, OWL.AnnotationProperty))
        g.add((prop, RDFS.label, Literal(local)))
        g.add((prop, RDFS.comment, Literal(comment, lang="en")))

    # Parent classes
    for local, label, comment in (
        ("Entity", "Entity", "Business entity backed by a dimension table"),
        ("Measure", "Measure", "KPI / measure / field concept linked to metric views"),
        (
            "AmbiguousTerm",
            "Ambiguous term",
            "Disambiguation term with no asset links; Genie should clarify",
        ),
    ):
        cls = EA[local]
        g.add((cls, RDF.type, OWL.Class))
        g.add((cls, RDFS.label, Literal(label, lang="en")))
        g.add((cls, RDFS.comment, Literal(comment, lang="en")))

    # Term classes in glossary order
    for term in terms:
        tid = term["id"]
        cls = term_uri(tid)
        parent = EA[classify_term(term)]

        g.add((cls, RDF.type, OWL.Class))
        g.add((cls, RDFS.subClassOf, parent))

        name = term.get("name") or tid
        g.add((cls, RDFS.label, Literal(str(name), lang="en")))

        definition = collapse_ws(term.get("definition") or "")
        if definition:
            g.add((cls, RDFS.comment, Literal(definition, lang="en")))

        owner = term.get("owner")
        if owner:
            g.add((cls, EA.ownedBy, Literal(str(owner))))

        # related → skos:related (sorted for determinism)
        for ref in sorted(term.get("related") or []):
            g.add((cls, SKOS.related, term_uri(ref)))

        # not_same_as → owl:disjointWith (sorted)
        for ref in sorted(term.get("not_same_as") or []):
            g.add((cls, OWL.disjointWith, term_uri(ref)))

        # links_to annotations (sorted by property IRI + value)
        annos: list[tuple[URIRef, str]] = []
        for link in term.get("links_to") or []:
            if not isinstance(link, dict):
                raise SystemExit(f"Term {tid!r}: links_to entry must be a mapping")
            annos.extend(link_annotations(link))
        for prop, value in sorted(annos, key=lambda x: (str(x[0]), x[1])):
            g.add((cls, prop, Literal(value)))

    add_object_properties(g, props)

    # Ensure all referenced ids exist as classes (already validated)
    _ = by_id
    return g


def serialize_turtle(g: Graph) -> str:
    """Deterministic Turtle: fixed prefixes, sorted triples via rdflib serializer."""
    # rdflib turtle is mostly stable when prefixes are bound; normalize newlines.
    raw = g.serialize(format="turtle")
    if isinstance(raw, bytes):
        text = raw.decode("utf-8")
    else:
        text = raw
    # Normalize line endings; strip trailing spaces; ensure single trailing newline
    lines = [ln.rstrip() for ln in text.replace("\r\n", "\n").replace("\r", "\n").split("\n")]
    body = "\n".join(lines).rstrip() + "\n"
    return HEADER_COMMENT + body


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if exec_analyst.ttl does not match glossary.yml + graph.yml",
    )
    args = parser.parse_args()

    terms = load_glossary(GLOSSARY_PATH)
    object_properties = load_object_properties(GRAPH_PATH)
    g = build_graph(terms, object_properties)
    ttl = serialize_turtle(g)

    if args.check:
        if not OUT_PATH.is_file():
            print(f"MISSING {OUT_PATH}", file=sys.stderr)
            return 1
        current = OUT_PATH.read_text(encoding="utf-8")
        if current != ttl:
            print(
                f"STALE {OUT_PATH.relative_to(REPO_ROOT)} — run: "
                f"python src/ontology/generate_owl.py",
                file=sys.stderr,
            )
            return 1
        print(
            f"OK {OUT_PATH.relative_to(REPO_ROOT)} matches glossary.yml + graph.yml"
        )
        return 0

    OUT_PATH.write_text(ttl, encoding="utf-8", newline="\n")
    print(f"Wrote {OUT_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
