#!/usr/bin/env python3
"""Generate every downstream ontology artifact from exec_analyst.ttl.

exec_analyst.ttl is the single source of truth (see its rdfs:comment on the
owl:Ontology node). This script reads it and regenerates:

  src/metric_views/tag_metric_views.sql   UC tags (domain/grain/kpi/glossary_terms)
  src/ontology/materialize_kg.sql         ontology.kg_nodes / kg_edges (ABox)
  src/ontology/grant_kg.sql               GRANT USAGE/SELECT on the KG schema
  src/ontology/kg_functions.sql           UC SQL functions for graph traversal
  src/ontology/kg_queries.sql             worked neighborhood queries (SQL editor)
  ontology_reference.html                 browsable class/property reference

Nothing below should be hand-edited; change exec_analyst.ttl and re-run.

Usage (from repo root):
  python src/ontology/generate.py
  python src/ontology/generate.py --check   # exit 1 if any output is stale
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass, field
from pathlib import Path

try:
    import rdflib
    from rdflib import RDF, RDFS, OWL, Namespace
except ImportError as e:  # pragma: no cover
    raise SystemExit("rdflib is required: pip install rdflib") from e

REPO_ROOT = Path(__file__).resolve().parents[2]
TTL_PATH = REPO_ROOT / "src" / "ontology" / "exec_analyst.ttl"
TTL_SOURCE = "src/ontology/exec_analyst.ttl"

MFG = Namespace("http://msil.example.org/ontology/automotive-manufacturing#")
EA = Namespace("https://focaloid.com/ontology/executive-analyst#")

OUT_TAGS = REPO_ROOT / "src" / "metric_views" / "tag_metric_views.sql"
OUT_KG = REPO_ROOT / "src" / "ontology" / "materialize_kg.sql"
OUT_GRANT_KG = REPO_ROOT / "src" / "ontology" / "grant_kg.sql"
OUT_KG_FUNCTIONS = REPO_ROOT / "src" / "ontology" / "kg_functions.sql"
OUT_KG_QUERIES = REPO_ROOT / "src" / "ontology" / "kg_queries.sql"
OUT_HTML = REPO_ROOT.parent / "ontology_reference.html"
OUT_GENIE_CTX = REPO_ROOT / "src" / "ontology" / "genie_context.json"
OUT_KG_INTEGRITY = REPO_ROOT / "src" / "tests" / "assert_kg_integrity.sql"
OUT_GENIE_SPACE = REPO_ROOT / "src" / "executive_analyst.geniespace.json"

# The Genie API allows at most one text_instructions item, so the ontology-derived
# block is appended to the hand-written instruction. Regenerating replaces everything
# from this marker onward and leaves the prose above it alone.
GENIE_ONTOLOGY_MARKER = "## Ontology grounding (generated)"

# The Genie space JSON hard-codes gold_dev identifiers (see README) — the generated
# instruction must name the kg_* functions the same way its sql_functions entries do.
GENIE_CATALOG = "gold_dev"

GENERATED_BANNER = (
    "GENERATED by src/ontology/generate.py from src/ontology/exec_analyst.ttl "
    "- do not edit by hand."
)


def local(uri: rdflib.term.URIRef | rdflib.term.BNode) -> str:
    return str(uri).rsplit("#", 1)[-1]


def literal(g: rdflib.Graph, s, p) -> str | None:
    v = g.value(s, p)
    return str(v) if v is not None else None


def literals(g: rdflib.Graph, s, p) -> list[str]:
    return [str(o) for o in g.objects(s, p)]


def ident(name: str) -> str:
    """Backtick-quote an identifier that is not a bare word.

    The five deployed metric views do not share a naming convention: revenue,
    marketing and manufacturing expose snake_case measures, while the two
    supply_chain views were rebuilt with Title Case names containing spaces
    ('Avg Days of Supply'). Those only resolve inside MEASURE() when quoted.
    """
    return name if name.replace("_", "").isalnum() else f"`{name}`"


@dataclass
class EntityClass:
    iri: rdflib.term.URIRef
    name: str
    comment: str
    table: str
    key_col: str
    name_col: str
    view: str | None
    field: str | None
    aka: list[str] = field(default_factory=list)


@dataclass
class KpiClass:
    iri: rdflib.term.URIRef
    name: str
    comment: str
    view: str
    measure: str | None
    view_field: str | None
    domain_tag: str | None
    grain_tag: str | None
    not_same_as: list[str] = field(default_factory=list)
    aka: list[str] = field(default_factory=list)


@dataclass
class GrainClass:
    """A Measurement/Event class bound only to a view + fact (defines domain/grain tags)."""

    iri: rdflib.term.URIRef
    name: str
    comment: str
    view: str
    fact: str
    domain_tag: str
    grain_tag: str


@dataclass
class AmbiguousTerm:
    iri: rdflib.term.URIRef
    name: str
    comment: str
    disambiguates_to: list[str]
    aka: list[str] = field(default_factory=list)


@dataclass
class EnumClass:
    iri: rdflib.term.URIRef
    name: str
    comment: str
    column: str | None
    values: list[str]
    aka: list[str] = field(default_factory=list)


@dataclass
class ObjectProperty:
    iri: rdflib.term.URIRef
    name: str
    comment: str
    domain_class: str
    range_class: str
    inverse_of: str | None
    edge_from: str | None
    edge_subject_key: str | None
    edge_object_key: str | None
    edge_filter: str | None


@dataclass
class Model:
    entities: list[EntityClass]
    kpis: list[KpiClass]
    grains: list[GrainClass]
    ambiguous: list[AmbiguousTerm]
    enums: list[EnumClass]
    object_properties: list[ObjectProperty]


def load_model(ttl_path: Path) -> Model:
    g = rdflib.Graph()
    g.parse(ttl_path, format="turtle")

    entities: list[EntityClass] = []
    kpis: list[KpiClass] = []
    grains: list[GrainClass] = []
    ambiguous: list[AmbiguousTerm] = []
    enums: list[EnumClass] = []
    object_properties: list[ObjectProperty] = []

    for cls in sorted(set(g.subjects(RDF.type, OWL.Class)), key=local):
        comment = literal(g, cls, RDFS.comment) or ""
        aka = literals(g, cls, EA.aka)
        table = literal(g, cls, EA.boundToTable)
        view = literal(g, cls, EA.boundToView)
        measure = literal(g, cls, EA.boundToMeasure)
        view_field = literal(g, cls, EA.boundToField)
        column = literal(g, cls, EA.boundToColumn)
        domain_tag = literal(g, cls, EA.domainTag)
        grain_tag = literal(g, cls, EA.grainTag)
        not_same_as = [local(o) for o in g.objects(cls, EA.notSameAs)]
        disambiguates_to = [local(o) for o in g.objects(cls, EA.disambiguatesTo)]

        is_ambiguous = (cls, RDFS.subClassOf, EA.AmbiguousTerm) in g
        is_kpi = (cls, RDFS.subClassOf, EA.KPI) in g
        oneof_values = _oneof_labels(g, cls)

        if is_ambiguous:
            ambiguous.append(
                AmbiguousTerm(cls, local(cls), comment, disambiguates_to, aka)
            )
        elif oneof_values:
            enums.append(EnumClass(cls, local(cls), comment, column, oneof_values, aka))
        elif is_kpi and view and measure:
            kpis.append(
                KpiClass(
                    cls, local(cls), comment, view, measure, view_field,
                    domain_tag, grain_tag, not_same_as, aka,
                )
            )
        elif table:
            entities.append(
                EntityClass(
                    cls, local(cls), comment, table,
                    literal(g, cls, EA.boundToKeyColumn) or "",
                    literal(g, cls, EA.boundToNameColumn) or "",
                    view, view_field, aka,
                )
            )
        elif view and column and domain_tag and grain_tag:
            fact = column  # ea:boundToColumn holds the bare fact table here
            grains.append(GrainClass(cls, local(cls), comment, view, fact, domain_tag, grain_tag))

    for prop in sorted(set(g.subjects(RDF.type, OWL.ObjectProperty)), key=local):
        edge_from = literal(g, prop, EA.edgeFrom)
        domain_c = g.value(prop, RDFS.domain)
        range_c = g.value(prop, RDFS.range)
        if domain_c is None or range_c is None:
            continue
        inv = g.value(prop, OWL.inverseOf)
        object_properties.append(
            ObjectProperty(
                prop, local(prop), literal(g, prop, RDFS.comment) or "",
                local(domain_c), local(range_c),
                local(inv) if inv is not None else None,
                edge_from,
                literal(g, prop, EA.edgeSubjectKey),
                literal(g, prop, EA.edgeObjectKey),
                literal(g, prop, EA.edgeFilter),
            )
        )

    return Model(entities, kpis, grains, ambiguous, enums, object_properties)


def _oneof_labels(g: rdflib.Graph, cls) -> list[str]:
    """Return rdfs:label values of an owl:oneOf enumeration's named individuals, in list order."""
    for eq in g.objects(cls, OWL.equivalentClass):
        for lst in g.objects(eq, OWL.oneOf):
            items = list(rdflib.collection.Collection(g, lst))
            return [literal(g, i, RDFS.label) or local(i) for i in items]
    return []


# ---------------------------------------------------------------------------
# tag_metric_views.sql — one ALTER VIEW per metric view, one ALTER TABLE per dim
# ---------------------------------------------------------------------------

def render_tags(model: Model) -> str:
    view_meta: dict[str, dict[str, str]] = {}
    view_terms: dict[str, list[str]] = {}
    table_terms: dict[str, list[str]] = {}

    for gr in model.grains:
        view_meta[gr.view] = {"domain": gr.domain_tag, "grain": gr.grain_tag}
        view_terms.setdefault(gr.view, [])

    for k in model.kpis:
        view_meta.setdefault(k.view, {"domain": k.domain_tag or "", "grain": k.grain_tag or ""})
        view_terms.setdefault(k.view, []).append(k.name)

    for e in model.entities:
        if e.view:
            view_terms.setdefault(e.view, []).append(e.name)
        if e.table not in table_terms:
            table_terms[e.table] = []
        table_terms[e.table].append(e.name)

    for view, meta in view_meta.items():
        if not meta.get("domain") or not meta.get("grain"):
            raise SystemExit(f"View {view!r} is missing a domain/grain tag in the TTL")

    lines = [
        "-- Tag the Executive Analyst metric views + linked dim tables for ontology wiring.",
        "-- Job param {{catalog}} expands to a quoted string (e.g. 'gold_dev'); concatenate into DDL.",
        f"-- {GENERATED_BANNER}",
        "",
        "-- --- Metric views ---",
        "",
    ]
    for view in sorted(view_meta):
        meta = view_meta[view]
        terms = ",".join(dict.fromkeys(view_terms.get(view, [])))
        lines += [
            "EXECUTE IMMEDIATE",
            f'"ALTER VIEW " || {{{{catalog}}}} || ".{view} SET TAGS (\n'
            f"  'domain' = '{meta['domain']}',\n"
            f"  'grain' = '{meta['grain']}',\n"
            f"  'kpi' = 'true',\n"
            f"  'glossary_source' = '{TTL_SOURCE}',\n"
            f"  'glossary_terms' = '{terms}'\n"
            f')";',
            "",
        ]

    lines += ["-- --- Dim tables (entity bindings) ---", ""]
    for table in sorted(table_terms):
        terms = ",".join(dict.fromkeys(table_terms[table]))
        lines += [
            "EXECUTE IMMEDIATE",
            f'"ALTER TABLE " || {{{{catalog}}}} || ".{table} SET TAGS (\n'
            f"  'glossary_source' = '{TTL_SOURCE}',\n"
            f"  'glossary_terms' = '{terms}'\n"
            f')";',
            "",
        ]
    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------------------
# materialize_kg.sql — kg_nodes (entities) + kg_edges (object properties)
# ---------------------------------------------------------------------------

def render_kg(model: Model) -> str:
    entity_by_name = {e.name: e for e in model.entities}

    header = [
        "-- Executive Analyst \u2014 Delta property graph (ABox), catalog.ontology schema.",
        "-- Navigation only: KPI math stays in metrics_*. Not a Genie data source.",
        f"-- {GENERATED_BANNER}",
        "-- Schema {{catalog}}.ontology must already exist (CREATE SCHEMA IF NOT EXISTS).",
        "",
        'EXECUTE IMMEDIATE "CREATE SCHEMA IF NOT EXISTS " || {{catalog}} || ".ontology";',
        "",
        "-- --- kg_nodes: one row per entity instance, tagged with its ontology class ---",
        "",
    ]

    node_parts = []
    for e in sorted(model.entities, key=lambda x: x.name):
        node_parts.append(
            f"  SELECT\n"
            f"    '{e.name}' AS node_type,\n"
            f"    CAST({e.key_col} AS STRING) AS node_key,\n"
            f"    CAST({e.name_col} AS STRING) AS node_name\n"
            f'  FROM " || {{{{catalog}}}} || ".{e.table}'
        )
    nodes_union = "\nUNION ALL\n".join(node_parts)

    lines = header[:]

    lines.append(
        "EXECUTE IMMEDIATE\n"
        + '"CREATE OR REPLACE TABLE " || {{catalog}} || ".ontology.kg_nodes AS\n'
        + nodes_union
        + '";'
    )
    lines.append("")

    lines += ["-- --- kg_edges: one row per object property, keyed off the source fact ---", ""]

    edge_parts = []
    seen_rels: set[str] = set()
    for p in model.object_properties:
        if not p.edge_from or p.name in seen_rels:
            continue
        seen_rels.add(p.name)
        subj = entity_by_name.get(p.domain_class)
        obj = entity_by_name.get(p.range_class)
        if subj is None or obj is None:
            continue
        filt = ""
        if p.edge_filter:
            filt = " WHERE " + p.edge_filter.replace("{source}", '" || {{catalog}} || ".' + p.edge_from)
        edge_parts.append(
            f"  SELECT DISTINCT\n"
            f"    '{p.name}' AS rel,\n"
            f"    '{p.domain_class}' AS subject_type,\n"
            f"    CAST({p.edge_subject_key} AS STRING) AS subject_key,\n"
            f"    '{p.range_class}' AS object_type,\n"
            f"    CAST({p.edge_object_key} AS STRING) AS object_key\n"
            f'  FROM " || {{{{catalog}}}} || ".{p.edge_from}" || "{filt}'
        )
    edges_union = "\nUNION ALL\n".join(edge_parts)
    lines.append(
        "EXECUTE IMMEDIATE\n"
        + '"CREATE OR REPLACE TABLE " || {{catalog}} || ".ontology.kg_edges AS\n'
        + edges_union
        + '";'
    )
    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------------------
# grant_kg.sql
# ---------------------------------------------------------------------------

def render_grant_kg() -> str:
    return (
        "-- Grant read access to the Executive Analyst knowledge graph.\n"
        "-- Job params: {{catalog}} and {{grant_group}} expand to quoted strings.\n"
        f"-- {GENERATED_BANNER}\n"
        "\n"
        'EXECUTE IMMEDIATE\n'
        '"GRANT USAGE ON SCHEMA " || {{catalog}} || ".ontology TO `" || {{grant_group}} || "`";\n'
        "\n"
        'EXECUTE IMMEDIATE\n'
        '"GRANT SELECT ON TABLE " || {{catalog}} || ".ontology.kg_nodes TO `" || {{grant_group}} || "`";\n'
        "\n"
        'EXECUTE IMMEDIATE\n'
        '"GRANT SELECT ON TABLE " || {{catalog}} || ".ontology.kg_edges TO `" || {{grant_group}} || "`";\n'
        "\n"
        "-- The Genie space calls these as sql_functions; without EXECUTE the reader group\n"
        "-- gets a permission error instead of an answer.\n"
        'EXECUTE IMMEDIATE\n'
        '"GRANT EXECUTE ON FUNCTION " || {{catalog}} || ".ontology.kg_find_node TO `" || {{grant_group}} || "`";\n'
        "\n"
        'EXECUTE IMMEDIATE\n'
        '"GRANT EXECUTE ON FUNCTION " || {{catalog}} || ".ontology.kg_neighbors TO `" || {{grant_group}} || "`";\n'
    )


# ---------------------------------------------------------------------------
# kg_functions.sql — UC SQL functions, registerable as Agent Bricks tools
# ---------------------------------------------------------------------------

def render_kg_functions(model: Model) -> str:
    rels = sorted({p.name for p in model.object_properties if p.edge_from})
    rel_list = ", ".join(f"'{r}'" for r in rels)
    return f"""-- Executive Analyst knowledge-graph traversal functions.
-- Register these as UC functions and add them as a Genie space "functions" data
-- source (or a Multi-Agent Supervisor tool) so the agent can answer relationship
-- questions the metric views cannot (no cross-domain join path at fact grain).
-- {GENERATED_BANNER}
-- Known rels materialized by materialize_kg.sql: {rel_list}
--
-- Parameters are p_-prefixed on purpose. A SQL UDF body resolves a bare name to a
-- COLUMN in scope before it resolves it to a parameter, so naming a parameter
-- node_type while joining kg_nodes silently rewrites `e.subject_type = node_type`
-- into `e.subject_type = n.node_type` and the function returns zero rows with no
-- error. Do not drop the prefix.

EXECUTE IMMEDIATE
"CREATE OR REPLACE FUNCTION " || {{{{catalog}}}} || ".ontology.kg_neighbors(
  p_node_type STRING COMMENT 'Ontology class, e.g. Plant, Part, Supplier',
  p_node_key STRING COMMENT 'Business key of the starting node',
  p_rel STRING DEFAULT NULL COMMENT 'Restrict to one relationship name. NULL returns all'
)
RETURNS TABLE (direction STRING, rel STRING, node_type STRING, node_key STRING, node_name STRING)
COMMENT 'One-hop neighbors of a knowledge-graph node in either direction, optionally filtered by relationship.'
RETURN
  SELECT 'out' AS direction, e.rel, e.object_type AS node_type, e.object_key AS node_key, n.node_name
  FROM " || {{{{catalog}}}} || ".ontology.kg_edges e
  JOIN " || {{{{catalog}}}} || ".ontology.kg_nodes n
    ON n.node_type = e.object_type AND n.node_key = e.object_key
  WHERE e.subject_type = p_node_type AND e.subject_key = p_node_key
    AND (p_rel IS NULL OR e.rel = p_rel)
  UNION ALL
  SELECT 'in' AS direction, e.rel, e.subject_type AS node_type, e.subject_key AS node_key, n.node_name
  FROM " || {{{{catalog}}}} || ".ontology.kg_edges e
  JOIN " || {{{{catalog}}}} || ".ontology.kg_nodes n
    ON n.node_type = e.subject_type AND n.node_key = e.subject_key
  WHERE e.object_type = p_node_type AND e.object_key = p_node_key
    AND (p_rel IS NULL OR e.rel = p_rel)";

EXECUTE IMMEDIATE
"CREATE OR REPLACE FUNCTION " || {{{{catalog}}}} || ".ontology.kg_find_node(
  p_search_name STRING COMMENT 'Business name or partial name to look up, e.g. a plant or supplier name'
)
RETURNS TABLE (node_type STRING, node_key STRING, node_name STRING)
COMMENT 'Resolve a business name to its knowledge-graph node(s) so kg_neighbors can be called on it.'
RETURN
  SELECT node_type, node_key, node_name
  FROM " || {{{{catalog}}}} || ".ontology.kg_nodes
  WHERE node_name ILIKE '%' || p_search_name || '%'";
"""
# ---------------------------------------------------------------------------
# Genie space — inject the ontology-derived grounding as one text_instruction.
# UC tags carry domain/grain/terms, but nothing in UC carries "these two are not
# the same thing", which is precisely what the agent keeps getting wrong.
# ---------------------------------------------------------------------------

def render_genie_instruction(model: Model) -> str:
    lines = [
        "## Ontology grounding (generated)",
        "",
        f"Generated from `{TTL_SOURCE}` — the ontology is the source of truth for what "
        "these terms mean. Do not re-derive a KPI in ad-hoc SQL when a bound measure exists.",
        "",
        "### Never substitute these for each other",
    ]
    seen: set[tuple[str, str]] = set()
    for k in model.kpis:
        for other in k.not_same_as:
            pair = tuple(sorted((k.name, other)))
            if pair in seen:
                continue
            seen.add(pair)
            lines.append(f"- **{pair[0]}** is not **{pair[1]}**.")

    lines += ["", "### Ask before querying these ambiguous words"]
    for a in sorted(model.ambiguous, key=lambda x: x.name):
        senses = ", ".join(f"`{s}`" for s in a.disambiguates_to)
        lines.append(f"- **{a.name.lower()}** → could mean {senses}. Ask which; do not guess a default.")

    lines += ["", "### Controlled vocabularies (exact column values)"]
    for e in sorted(model.enums, key=lambda x: x.name):
        vals = ", ".join(f"`{v}`" for v in e.values)
        col = f" in `{e.column}`" if e.column else ""
        lines.append(f"- **{e.name}**{col}: {vals}")

    lines += ["", "### Governed measures (use MEASURE(), never a hand-rolled formula)"]
    for k in sorted(model.kpis, key=lambda x: x.name):
        lines.append(f"- **{k.name}** → `MEASURE({ident(k.measure)})` in `{k.view}`")

    rels = sorted({p.name for p in model.object_properties if p.edge_from})
    lines += [
        "",
        "### Relationship questions",
        "The metric views share no join path across domains. For questions about how "
        "entities connect (which lines a plant has, which suppliers feed a part, which "
        "dealers sell a model), use the knowledge-graph functions instead of inventing a JOIN:",
        f"- `{GENIE_CATALOG}.ontology.kg_find_node('<business name>')` resolves a name to its node.",
        f"- `{GENIE_CATALOG}.ontology.kg_neighbors('<NodeType>', '<node_key>', '<rel>')` "
        "walks one hop; omit the relation for all of them.",
        f"- Available relations: {', '.join('`' + r + '`' for r in rels)}.",
        "Never use these for KPI math — they carry structure only, no measures.",
    ]
    return "\n".join(lines)


def render_genie_space(model: Model) -> str:
    """Patch the ontology instruction into the hand-maintained Genie space file.

    The Genie API rejects more than one text_instructions item, so the generated
    block is appended to the single hand-written instruction, split off again on
    GENIE_ONTOLOGY_MARKER. Everything above the marker is hand-maintained.
    """
    spec = json.loads(OUT_GENIE_SPACE.read_text(encoding="utf-8"))
    entries = spec.setdefault("instructions", {}).setdefault("text_instructions", [])
    if not entries:
        raise SystemExit(
            f"{OUT_GENIE_SPACE.name}: expected one hand-written text_instruction to append to"
        )
    prose = "\n".join(entries[0].get("content", []))
    block = render_genie_instruction(model)
    entries[0]["content"] = [prose.split(GENIE_ONTOLOGY_MARKER)[0].rstrip() + "\n\n" + block]
    del entries[1:]
    return json.dumps(spec, indent=2, ensure_ascii=False) + "\n"


# ---------------------------------------------------------------------------
# assert_kg_integrity.sql — data-level gate; test_generate.py only checks the model
# ---------------------------------------------------------------------------

def render_kg_integrity(model: Model) -> str:
    edges = [p for p in model.object_properties if p.edge_from]
    rel_list = ", ".join(f"'{p.name}'" for p in sorted(edges, key=lambda p: p.name))
    type_list = ", ".join(f"'{e.name}'" for e in sorted(model.entities, key=lambda e: e.name))
    # (rel, domain, range) triples the TTL declares — anything else is a violation
    pairs = " OR ".join(
        f"(e.rel = '{p.name}' AND (e.subject_type <> '{p.domain_class}' "
        f"OR e.object_type <> '{p.range_class}'))"
        for p in sorted(edges, key=lambda p: p.name)
    )
    return f"""-- Verify {{{{catalog}}}}.ontology.kg_nodes / kg_edges agree with the TBox in
-- src/ontology/exec_analyst.ttl. src/ontology/test_generate.py checks the MODEL;
-- this checks the DATA that the model produced. Job param {{{{catalog}}}} expands
-- to a quoted string (e.g. 'gold_dev').
-- {GENERATED_BANNER}
--
-- Checks:
--   1. No orphan edges — every subject/object must resolve to a kg_nodes row.
--   2. No duplicate (node_type, node_key) — that pair is the graph's primary key.
--   3. Every rel is one the TTL declares.
--   4. Every edge's (subject_type, object_type) matches that rel's declared
--      rdfs:domain / rdfs:range.
--   5. No declared entity class or relation materialized to zero rows — a silently
--      empty union is the failure mode a row-count-blind check would miss.

-- --- Diagnostic (run ad hoc in the SQL editor; 0 rows = pass) ---

EXECUTE IMMEDIATE
"SELECT check_name, detail FROM (
  SELECT 'orphan_edge_subject' AS check_name,
    concat_ws(' ', e.rel, e.subject_type, e.subject_key) AS detail
  FROM " || {{{{catalog}}}} || ".ontology.kg_edges e
  LEFT JOIN " || {{{{catalog}}}} || ".ontology.kg_nodes n
    ON n.node_type = e.subject_type AND n.node_key = e.subject_key
  WHERE n.node_key IS NULL

  UNION ALL
  SELECT 'orphan_edge_object',
    concat_ws(' ', e.rel, e.object_type, e.object_key)
  FROM " || {{{{catalog}}}} || ".ontology.kg_edges e
  LEFT JOIN " || {{{{catalog}}}} || ".ontology.kg_nodes n
    ON n.node_type = e.object_type AND n.node_key = e.object_key
  WHERE n.node_key IS NULL

  UNION ALL
  SELECT 'duplicate_node', concat_ws(' ', node_type, node_key)
  FROM " || {{{{catalog}}}} || ".ontology.kg_nodes
  GROUP BY node_type, node_key HAVING COUNT(*) > 1

  UNION ALL
  SELECT 'unknown_rel', rel
  FROM " || {{{{catalog}}}} || ".ontology.kg_edges
  WHERE rel NOT IN ({rel_list})
  GROUP BY rel

  UNION ALL
  SELECT 'unknown_node_type', node_type
  FROM " || {{{{catalog}}}} || ".ontology.kg_nodes
  WHERE node_type NOT IN ({type_list})
  GROUP BY node_type

  UNION ALL
  SELECT 'domain_range_violation',
    concat_ws(' ', e.rel, ':', e.subject_type, '->', e.object_type)
  FROM " || {{{{catalog}}}} || ".ontology.kg_edges e
  WHERE {pairs}
  GROUP BY e.rel, e.subject_type, e.object_type

  UNION ALL
  SELECT 'empty_node_type', t.node_type
  FROM (SELECT explode(array({type_list})) AS node_type) t
  LEFT JOIN " || {{{{catalog}}}} || ".ontology.kg_nodes n ON n.node_type = t.node_type
  GROUP BY t.node_type HAVING COUNT(n.node_key) = 0

  UNION ALL
  SELECT 'empty_rel', r.rel
  FROM (SELECT explode(array({rel_list})) AS rel) r
  LEFT JOIN " || {{{{catalog}}}} || ".ontology.kg_edges e ON e.rel = r.rel
  GROUP BY r.rel HAVING COUNT(e.rel) = 0
) ORDER BY check_name, detail";

-- --- Assertion (job task; raise_error fails the run) ---

EXECUTE IMMEDIATE
"WITH violations AS (
  SELECT 'orphan_edge_subject' AS check_name
  FROM " || {{{{catalog}}}} || ".ontology.kg_edges e
  LEFT JOIN " || {{{{catalog}}}} || ".ontology.kg_nodes n
    ON n.node_type = e.subject_type AND n.node_key = e.subject_key
  WHERE n.node_key IS NULL

  UNION ALL
  SELECT 'orphan_edge_object'
  FROM " || {{{{catalog}}}} || ".ontology.kg_edges e
  LEFT JOIN " || {{{{catalog}}}} || ".ontology.kg_nodes n
    ON n.node_type = e.object_type AND n.node_key = e.object_key
  WHERE n.node_key IS NULL

  UNION ALL
  SELECT 'duplicate_node'
  FROM " || {{{{catalog}}}} || ".ontology.kg_nodes
  GROUP BY node_type, node_key HAVING COUNT(*) > 1

  UNION ALL
  SELECT 'unknown_rel'
  FROM " || {{{{catalog}}}} || ".ontology.kg_edges
  WHERE rel NOT IN ({rel_list})

  UNION ALL
  SELECT 'unknown_node_type'
  FROM " || {{{{catalog}}}} || ".ontology.kg_nodes
  WHERE node_type NOT IN ({type_list})

  UNION ALL
  SELECT 'domain_range_violation'
  FROM " || {{{{catalog}}}} || ".ontology.kg_edges e
  WHERE {pairs}

  UNION ALL
  SELECT 'empty_node_type'
  FROM (SELECT explode(array({type_list})) AS node_type) t
  LEFT JOIN " || {{{{catalog}}}} || ".ontology.kg_nodes n ON n.node_type = t.node_type
  GROUP BY t.node_type HAVING COUNT(n.node_key) = 0

  UNION ALL
  SELECT 'empty_rel'
  FROM (SELECT explode(array({rel_list})) AS rel) r
  LEFT JOIN " || {{{{catalog}}}} || ".ontology.kg_edges e ON e.rel = r.rel
  GROUP BY r.rel HAVING COUNT(e.rel) = 0
)
SELECT CASE WHEN COUNT(*) = 0
  THEN 'PASS: kg_nodes/kg_edges match the TBox ({len(model.entities)} classes, {len(edges)} relations)'
  ELSE raise_error(concat('FAIL: knowledge-graph integrity violated: ', concat_ws(', ', collect_set(check_name))))
END AS result
FROM violations";
"""


# ---------------------------------------------------------------------------
# kg_queries.sql — hand-readable worked examples (not a job task)
# ---------------------------------------------------------------------------

def render_kg_queries(model: Model) -> str:
    edges_seen = []
    for p in model.object_properties:
        if p.edge_from and p.name not in {e[0] for e in edges_seen}:
            edges_seen.append((p.name, p.domain_class, p.range_class))
    lines = [
        "-- Executive Analyst knowledge graph — worked neighborhood queries.",
        "-- Run in the SQL editor against {catalog}.ontology.kg_nodes / kg_edges.",
        f"-- {GENERATED_BANNER}",
        "",
        "-- Row counts by class / relationship",
        "SELECT node_type, COUNT(*) AS n FROM {catalog}.ontology.kg_nodes GROUP BY node_type ORDER BY 1;",
        "SELECT rel, COUNT(*) AS n FROM {catalog}.ontology.kg_edges GROUP BY rel ORDER BY 1;",
        "",
        "-- Orphan edges (endpoint missing from kg_nodes -- should return 0 rows)",
        "SELECT e.* FROM {catalog}.ontology.kg_edges e",
        "LEFT JOIN {catalog}.ontology.kg_nodes s ON s.node_type = e.subject_type AND s.node_key = e.subject_key",
        "LEFT JOIN {catalog}.ontology.kg_nodes o ON o.node_type = e.object_type AND o.node_key = e.object_key",
        "WHERE s.node_key IS NULL OR o.node_key IS NULL;",
        "",
    ]
    for rel, dom, rng in edges_seen:
        lines += [
            f"-- {dom} --[{rel}]--> {rng}: sample of 10",
            f"SELECT * FROM {{catalog}}.ontology.kg_edges WHERE rel = '{rel}' LIMIT 10;",
            "",
        ]
    lines += [
        "-- Two-hop example via UC functions (once kg_functions.sql is deployed):",
        "-- SELECT * FROM {catalog}.ontology.kg_find_node('Chennai');",
        "-- SELECT * FROM {catalog}.ontology.kg_neighbors('Plant', '<plant_key>', 'plantProducesModel');",
    ]
    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------------------
# ontology_reference.html — minimal browsable class/property reference
# ---------------------------------------------------------------------------

def _esc(s: str) -> str:
    return (s or "").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def render_html(model: Model) -> str:
    def card(title: str, kind: str, body: str) -> str:
        return (
            f'<div class="card {kind}"><h3>{_esc(title)} '
            f'<span class="tag {kind}">{kind}</span></h3>{body}</div>'
        )

    entity_cards = "\n".join(
        card(
            e.name, "entity",
            f'<p>{_esc(e.comment)}</p>'
            f'<p class="bind">bound to <code>{_esc(e.table)}</code> '
            f'(key <code>{_esc(e.key_col)}</code>, name <code>{_esc(e.name_col)}</code>)'
            + (f', view <code>{_esc(e.view)}</code>' if e.view else "") + '</p>'
            + (f'<p class="aka">aka: {_esc(", ".join(e.aka))}</p>' if e.aka else ""),
        )
        for e in sorted(model.entities, key=lambda x: x.name)
    )

    kpi_cards = "\n".join(
        card(
            k.name, "kpi",
            f'<p>{_esc(k.comment)}</p>'
            f'<p class="bind">MEASURE(<code>{_esc(k.measure)}</code>) in <code>{_esc(k.view)}</code></p>'
            + (f'<p class="notsame">not the same as: {_esc(", ".join(k.not_same_as))}</p>' if k.not_same_as else "")
            + (f'<p class="aka">aka: {_esc(", ".join(k.aka))}</p>' if k.aka else ""),
        )
        for k in sorted(model.kpis, key=lambda x: x.name)
    )

    ambiguous_cards = "\n".join(
        card(
            a.name, "ambiguous",
            f'<p>{_esc(a.comment)}</p>'
            f'<p class="bind">disambiguates to: {_esc(", ".join(a.disambiguates_to))}</p>',
        )
        for a in sorted(model.ambiguous, key=lambda x: x.name)
    )

    enum_cards = "\n".join(
        card(
            e.name, "enum",
            f'<p>{_esc(e.comment)}</p>'
            + (f'<p class="bind">column <code>{_esc(e.column)}</code></p>' if e.column else "")
            + f'<p class="values">values: {_esc(", ".join(e.values))}</p>',
        )
        for e in sorted(model.enums, key=lambda x: x.name)
    )

    prop_rows = "\n".join(
        f'<tr><td><code>{_esc(p.name)}</code></td><td>{_esc(p.domain_class)}</td>'
        f'<td>{_esc(p.range_class)}</td><td>{_esc(p.inverse_of or "")}</td>'
        f'<td>{_esc(p.comment)}</td></tr>'
        for p in sorted(model.object_properties, key=lambda x: x.name)
    )

    return f'''<!doctype html>
<html><head><meta charset="utf-8">
<title>Executive Analyst Ontology Reference</title>
<style>
:root {{ --bg:#f5f6f8; --ink:#14181f; --ink-soft:#565f72; --line:#d8dce4; --surface:#fff;
  --entity:#3a4a63; --kpi:#0e7c86; --ambiguous:#a1650f; --enum:#6b4fa0; }}
@media (prefers-color-scheme: dark) {{
  :root {{ --bg:#0b0e14; --ink:#e8ebf1; --ink-soft:#9aa3b5; --line:#29303f; --surface:#12161f; }}
}}
body {{ background:var(--bg); color:var(--ink); font-family:system-ui,sans-serif; margin:0; padding:2rem; line-height:1.5; }}
h1 {{ font-size:1.4rem; }}
h2 {{ margin-top:2.5rem; border-bottom:1px solid var(--line); padding-bottom:.3rem; }}
p.note {{ color:var(--ink-soft); max-width:60rem; }}
.grid {{ display:grid; grid-template-columns:repeat(auto-fill,minmax(300px,1fr)); gap:1rem; }}
.card {{ background:var(--surface); border:1px solid var(--line); border-left-width:4px; border-radius:6px; padding:.9rem 1rem; }}
.card.entity {{ border-left-color:var(--entity); }}
.card.kpi {{ border-left-color:var(--kpi); }}
.card.ambiguous {{ border-left-color:var(--ambiguous); }}
.card.enum {{ border-left-color:var(--enum); }}
.card h3 {{ margin:0 0 .4rem; font-size:1rem; }}
.tag {{ font-size:.65rem; text-transform:uppercase; padding:.1rem .4rem; border-radius:3px; color:#fff; float:right; }}
.tag.entity {{ background:var(--entity); }} .tag.kpi {{ background:var(--kpi); }}
.tag.ambiguous {{ background:var(--ambiguous); }} .tag.enum {{ background:var(--enum); }}
.card p {{ margin:.3rem 0; font-size:.88rem; }}
.bind, .notsame, .values, .aka {{ color:var(--ink-soft); }}
code {{ font-family:ui-monospace,monospace; }}
table {{ border-collapse:collapse; width:100%; font-size:.85rem; }}
td, th {{ border:1px solid var(--line); padding:.35rem .5rem; text-align:left; }}
</style></head>
<body>
<h1>Executive Analyst Ontology Reference</h1>
<p class="note">Rendered directly from <code>{_esc(TTL_SOURCE)}</code> by
<code>src/ontology/generate.py</code> — this page can never drift from the machine-readable
model. Scope: only the assets the Executive Analyst Genie space is connected to.</p>

<h2>Entities ({len(model.entities)})</h2>
<div class="grid">{entity_cards}</div>

<h2>KPIs ({len(model.kpis)})</h2>
<div class="grid">{kpi_cards}</div>

<h2>Ambiguous terms ({len(model.ambiguous)})</h2>
<div class="grid">{ambiguous_cards}</div>

<h2>Controlled vocabularies / enums ({len(model.enums)})</h2>
<div class="grid">{enum_cards}</div>

<h2>Object properties ({len(model.object_properties)})</h2>
<table>
<tr><th>property</th><th>domain</th><th>range</th><th>inverse of</th><th>comment</th></tr>
{prop_rows}
</table>
</body></html>
'''


# ---------------------------------------------------------------------------
# genie_context.json — synonyms, enum values, not_same_as, disambiguations
# ---------------------------------------------------------------------------

def render_genie_context(model: Model) -> str:
    """Emit a structured JSON object consumed by the Genie Knowledge Store.

    Sections:
      synonyms        — ea:aka on every named class (entities, KPIs, enums, grains)
      enum_values     — owl:oneOf closed enumerations with column binding
      not_same_as     — pairs of concepts users routinely conflate
      disambiguates_to — ambiguous surface terms and their candidate concepts
    """
    synonyms: list[dict] = []
    not_same_as: list[dict] = []
    disambiguates_to: list[dict] = []
    enum_values: list[dict] = []

    # Entities
    for e in sorted(model.entities, key=lambda x: x.name):
        if e.aka:
            synonyms.append({"term": e.name, "kind": "entity", "synonyms": e.aka})

    # KPIs
    for k in sorted(model.kpis, key=lambda x: x.name):
        if k.aka:
            synonyms.append({"term": k.name, "kind": "kpi", "synonyms": k.aka})
        if k.not_same_as:
            not_same_as.append({"term": k.name, "not_same_as": k.not_same_as})

    # Enums
    for e in sorted(model.enums, key=lambda x: x.name):
        entry: dict = {"class": e.name, "values": e.values}
        if e.column:
            entry["column"] = e.column
        if e.aka:
            synonyms.append({"term": e.name, "kind": "enum", "synonyms": e.aka})
        enum_values.append(entry)

    # Ambiguous terms
    for a in sorted(model.ambiguous, key=lambda x: x.name):
        if a.aka:
            synonyms.append({"term": a.name, "kind": "ambiguous", "synonyms": a.aka})
        disambiguates_to.append({"term": a.name, "options": a.disambiguates_to})

    ctx = {
        "_comment": GENERATED_BANNER,
        "generated_from": TTL_SOURCE,
        "synonyms": synonyms,
        "enum_values": enum_values,
        "not_same_as": not_same_as,
        "disambiguates_to": disambiguates_to,
    }
    return json.dumps(ctx, indent=2, ensure_ascii=False) + "\n"


# ---------------------------------------------------------------------------
# driver
# ---------------------------------------------------------------------------

TARGETS: list[tuple[Path, "callable"]] = []


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Exit 1 if any output is stale")
    args = parser.parse_args()

    if not TTL_PATH.is_file():
        raise SystemExit(f"Missing {TTL_PATH}")

    model = load_model(TTL_PATH)

    outputs = {
        OUT_TAGS: render_tags(model),
        OUT_KG: render_kg(model),
        OUT_GRANT_KG: render_grant_kg(),
        OUT_KG_FUNCTIONS: render_kg_functions(model),
        OUT_KG_QUERIES: render_kg_queries(model),
        OUT_HTML: render_html(model),
        OUT_GENIE_CTX: render_genie_context(model),
        OUT_KG_INTEGRITY: render_kg_integrity(model),
        OUT_GENIE_SPACE: render_genie_space(model),
    }

    if args.check:
        stale = []
        for path, content in outputs.items():
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                stale.append(path)
        if stale:
            for p in stale:
                print(f"STALE {p}", file=sys.stderr)
            print("Run: python src/ontology/generate.py", file=sys.stderr)
            return 1
        print("OK all generated ontology artifacts match exec_analyst.ttl")
        return 0

    for path, content in outputs.items():
        path.write_text(content, encoding="utf-8", newline="\n")
        print(f"Wrote {path.relative_to(REPO_ROOT.parent)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
