-- Grant read access to the Executive Analyst knowledge graph.
-- Job params: {{catalog}} and {{grant_group}} expand to quoted strings.
-- GENERATED by src/ontology/generate.py from src/ontology/exec_analyst.ttl - do not edit by hand.

EXECUTE IMMEDIATE
"GRANT USAGE ON SCHEMA " || {{catalog}} || ".ontology TO `" || {{grant_group}} || "`";

EXECUTE IMMEDIATE
"GRANT SELECT ON TABLE " || {{catalog}} || ".ontology.kg_nodes TO `" || {{grant_group}} || "`";

EXECUTE IMMEDIATE
"GRANT SELECT ON TABLE " || {{catalog}} || ".ontology.kg_edges TO `" || {{grant_group}} || "`";

-- The Genie space calls these as sql_functions; without EXECUTE the reader group
-- gets a permission error instead of an answer.
EXECUTE IMMEDIATE
"GRANT EXECUTE ON FUNCTION " || {{catalog}} || ".ontology.kg_find_node TO `" || {{grant_group}} || "`";

EXECUTE IMMEDIATE
"GRANT EXECUTE ON FUNCTION " || {{catalog}} || ".ontology.kg_neighbors TO `" || {{grant_group}} || "`";
