-- Executive Analyst knowledge-graph traversal functions.
-- Register these as UC functions and add them as a Genie space "functions" data
-- source (or a Multi-Agent Supervisor tool) so the agent can answer relationship
-- questions the metric views cannot (no cross-domain join path at fact grain).
-- GENERATED by src/ontology/generate.py from src/ontology/exec_analyst.ttl - do not edit by hand.
-- Known rels materialized by materialize_kg.sql: 'campaignRunsOnChannel', 'campaignTargetsSegment', 'lineProducesModel', 'partStockedAt', 'plantHasLine', 'plantProducesModel', 'supplierSuppliesPart'
--
-- Parameters are p_-prefixed on purpose. A SQL UDF body resolves a bare name to a
-- COLUMN in scope before it resolves it to a parameter, so naming a parameter
-- node_type while joining kg_nodes silently rewrites `e.subject_type = node_type`
-- into `e.subject_type = n.node_type` and the function returns zero rows with no
-- error. Do not drop the prefix.

EXECUTE IMMEDIATE
"CREATE OR REPLACE FUNCTION " || {{catalog}} || ".ontology.kg_neighbors(
  p_node_type STRING COMMENT 'Ontology class, e.g. Plant, Part, Supplier',
  p_node_key STRING COMMENT 'Business key of the starting node',
  p_rel STRING DEFAULT NULL COMMENT 'Restrict to one relationship name. NULL returns all'
)
RETURNS TABLE (direction STRING, rel STRING, node_type STRING, node_key STRING, node_name STRING)
COMMENT 'One-hop neighbors of a knowledge-graph node in either direction, optionally filtered by relationship.'
RETURN
  SELECT 'out' AS direction, e.rel, e.object_type AS node_type, e.object_key AS node_key, n.node_name
  FROM " || {{catalog}} || ".ontology.kg_edges e
  JOIN " || {{catalog}} || ".ontology.kg_nodes n
    ON n.node_type = e.object_type AND n.node_key = e.object_key
  WHERE e.subject_type = p_node_type AND e.subject_key = p_node_key
    AND (p_rel IS NULL OR e.rel = p_rel)
  UNION ALL
  SELECT 'in' AS direction, e.rel, e.subject_type AS node_type, e.subject_key AS node_key, n.node_name
  FROM " || {{catalog}} || ".ontology.kg_edges e
  JOIN " || {{catalog}} || ".ontology.kg_nodes n
    ON n.node_type = e.subject_type AND n.node_key = e.subject_key
  WHERE e.object_type = p_node_type AND e.object_key = p_node_key
    AND (p_rel IS NULL OR e.rel = p_rel)";

EXECUTE IMMEDIATE
"CREATE OR REPLACE FUNCTION " || {{catalog}} || ".ontology.kg_find_node(
  p_search_name STRING COMMENT 'Business name or partial name to look up, e.g. a plant or supplier name'
)
RETURNS TABLE (node_type STRING, node_key STRING, node_name STRING)
COMMENT 'Resolve a business name to its knowledge-graph node(s) so kg_neighbors can be called on it.'
RETURN
  SELECT node_type, node_key, node_name
  FROM " || {{catalog}} || ".ontology.kg_nodes
  WHERE node_name ILIKE '%' || p_search_name || '%'";
