-- Executive Analyst knowledge graph — worked neighborhood queries.
-- Run in the SQL editor against {catalog}.ontology.kg_nodes / kg_edges.
-- GENERATED by src/ontology/generate.py from src/ontology/exec_analyst.ttl - do not edit by hand.

-- Row counts by class / relationship
SELECT node_type, COUNT(*) AS n FROM {catalog}.ontology.kg_nodes GROUP BY node_type ORDER BY 1;
SELECT rel, COUNT(*) AS n FROM {catalog}.ontology.kg_edges GROUP BY rel ORDER BY 1;

-- Orphan edges (endpoint missing from kg_nodes -- should return 0 rows)
SELECT e.* FROM {catalog}.ontology.kg_edges e
LEFT JOIN {catalog}.ontology.kg_nodes s ON s.node_type = e.subject_type AND s.node_key = e.subject_key
LEFT JOIN {catalog}.ontology.kg_nodes o ON o.node_type = e.object_type AND o.node_key = e.object_key
WHERE s.node_key IS NULL OR o.node_key IS NULL;

-- MarketingCampaign --[campaignRunsOnChannel]--> CampaignChannel: sample of 10
SELECT * FROM {catalog}.ontology.kg_edges WHERE rel = 'campaignRunsOnChannel' LIMIT 10;

-- MarketingCampaign --[campaignTargetsSegment]--> CustomerSegment: sample of 10
SELECT * FROM {catalog}.ontology.kg_edges WHERE rel = 'campaignTargetsSegment' LIMIT 10;

-- ProductionLine --[lineProducesModel]--> VehicleModel: sample of 10
SELECT * FROM {catalog}.ontology.kg_edges WHERE rel = 'lineProducesModel' LIMIT 10;

-- Part --[partStockedAt]--> Warehouse: sample of 10
SELECT * FROM {catalog}.ontology.kg_edges WHERE rel = 'partStockedAt' LIMIT 10;

-- Plant --[plantHasLine]--> ProductionLine: sample of 10
SELECT * FROM {catalog}.ontology.kg_edges WHERE rel = 'plantHasLine' LIMIT 10;

-- Plant --[plantProducesModel]--> VehicleModel: sample of 10
SELECT * FROM {catalog}.ontology.kg_edges WHERE rel = 'plantProducesModel' LIMIT 10;

-- Supplier --[supplierSuppliesPart]--> Part: sample of 10
SELECT * FROM {catalog}.ontology.kg_edges WHERE rel = 'supplierSuppliesPart' LIMIT 10;

-- Two-hop example via UC functions (once kg_functions.sql is deployed):
-- SELECT * FROM {catalog}.ontology.kg_find_node('Chennai');
-- SELECT * FROM {catalog}.ontology.kg_neighbors('Plant', '<plant_key>', 'plantProducesModel');
