-- Executive Analyst — Delta property graph (ABox), catalog.ontology schema.
-- Navigation only: KPI math stays in metrics_*. Not a Genie data source.
-- GENERATED by src/ontology/generate.py from src/ontology/exec_analyst.ttl - do not edit by hand.
-- Schema {{catalog}}.ontology must already exist (CREATE SCHEMA IF NOT EXISTS).

EXECUTE IMMEDIATE "CREATE SCHEMA IF NOT EXISTS " || {{catalog}} || ".ontology";

-- --- kg_nodes: one row per entity instance, tagged with its ontology class ---

EXECUTE IMMEDIATE
"CREATE OR REPLACE TABLE " || {{catalog}} || ".ontology.kg_nodes AS
  SELECT
    'CalendarDate' AS node_type,
    CAST(DATE_KEY AS STRING) AS node_key,
    CAST(FULL_DATE AS STRING) AS node_name
  FROM " || {{catalog}} || ".dim.dim_date
UNION ALL
  SELECT
    'CampaignChannel' AS node_type,
    CAST(CHANNEL_KEY AS STRING) AS node_key,
    CAST(CHANNEL_NAME AS STRING) AS node_name
  FROM " || {{catalog}} || ".dim.dim_channel
UNION ALL
  SELECT
    'CustomerSegment' AS node_type,
    CAST(SEGMENT_KEY AS STRING) AS node_key,
    CAST(SEGMENT_NAME AS STRING) AS node_name
  FROM " || {{catalog}} || ".dim.dim_customer_segment
UNION ALL
  SELECT
    'Dealer' AS node_type,
    CAST(DEALER_KEY AS STRING) AS node_key,
    CAST(DEALER_NAME AS STRING) AS node_name
  FROM " || {{catalog}} || ".dim.dim_dealer
UNION ALL
  SELECT
    'MarketingCampaign' AS node_type,
    CAST(CAMPAIGN_KEY AS STRING) AS node_key,
    CAST(CAMPAIGN_NAME AS STRING) AS node_name
  FROM " || {{catalog}} || ".dim.dim_campaign
UNION ALL
  SELECT
    'Part' AS node_type,
    CAST(PART_KEY AS STRING) AS node_key,
    CAST(PART_NAME AS STRING) AS node_name
  FROM " || {{catalog}} || ".dim.dim_part
UNION ALL
  SELECT
    'Plant' AS node_type,
    CAST(PLANT_KEY AS STRING) AS node_key,
    CAST(PLANT_NAME AS STRING) AS node_name
  FROM " || {{catalog}} || ".dim.dim_plant
UNION ALL
  SELECT
    'ProductionLine' AS node_type,
    CAST(LINE_KEY AS STRING) AS node_key,
    CAST(LINE_NAME AS STRING) AS node_name
  FROM " || {{catalog}} || ".dim.dim_production_line
UNION ALL
  SELECT
    'Supplier' AS node_type,
    CAST(SUPPLIER_KEY AS STRING) AS node_key,
    CAST(SUPPLIER_NAME AS STRING) AS node_name
  FROM " || {{catalog}} || ".dim.dim_supplier
UNION ALL
  SELECT
    'VehicleModel' AS node_type,
    CAST(MODEL_KEY AS STRING) AS node_key,
    CAST(MODEL_NAME AS STRING) AS node_name
  FROM " || {{catalog}} || ".dim.dim_vehicle_model
UNION ALL
  SELECT
    'Warehouse' AS node_type,
    CAST(WAREHOUSE_KEY AS STRING) AS node_key,
    CAST(WAREHOUSE_NAME AS STRING) AS node_name
  FROM " || {{catalog}} || ".dim.dim_warehouse";

-- --- kg_edges: one row per object property, keyed off the source fact ---

EXECUTE IMMEDIATE
"CREATE OR REPLACE TABLE " || {{catalog}} || ".ontology.kg_edges AS
  SELECT DISTINCT
    'campaignRunsOnChannel' AS rel,
    'MarketingCampaign' AS subject_type,
    CAST(CAMPAIGN_KEY AS STRING) AS subject_key,
    'CampaignChannel' AS object_type,
    CAST(CHANNEL_KEY AS STRING) AS object_key
  FROM " || {{catalog}} || ".marketing_analytics.fact_campaign_performance" || "
UNION ALL
  SELECT DISTINCT
    'campaignTargetsSegment' AS rel,
    'MarketingCampaign' AS subject_type,
    CAST(CAMPAIGN_KEY AS STRING) AS subject_key,
    'CustomerSegment' AS object_type,
    CAST(SEGMENT_KEY AS STRING) AS object_key
  FROM " || {{catalog}} || ".marketing_analytics.fact_campaign_performance" || "
UNION ALL
  SELECT DISTINCT
    'dealerSellsModel' AS rel,
    'Dealer' AS subject_type,
    CAST(DEALER_KEY AS STRING) AS subject_key,
    'VehicleModel' AS object_type,
    CAST(MODEL_KEY AS STRING) AS object_key
  FROM " || {{catalog}} || ".revenue_analytics.fact_sales_order" || "
UNION ALL
  SELECT DISTINCT
    'lineProducesModel' AS rel,
    'ProductionLine' AS subject_type,
    CAST(LINE_KEY AS STRING) AS subject_key,
    'VehicleModel' AS object_type,
    CAST(MODEL_KEY AS STRING) AS object_key
  FROM " || {{catalog}} || ".manufacturing_analytics.fact_production_execution" || "
UNION ALL
  SELECT DISTINCT
    'partStockedAt' AS rel,
    'Part' AS subject_type,
    CAST(PART_KEY AS STRING) AS subject_key,
    'Warehouse' AS object_type,
    CAST(WAREHOUSE_KEY AS STRING) AS object_key
  FROM " || {{catalog}} || ".supply_chain_analytics.fact_inventory_snapshot" || " WHERE SNAPSHOT_DATE_KEY = (SELECT MAX(SNAPSHOT_DATE_KEY) FROM " || {{catalog}} || ".supply_chain_analytics.fact_inventory_snapshot)
UNION ALL
  SELECT DISTINCT
    'plantHasLine' AS rel,
    'Plant' AS subject_type,
    CAST(PLANT_KEY AS STRING) AS subject_key,
    'ProductionLine' AS object_type,
    CAST(LINE_KEY AS STRING) AS object_key
  FROM " || {{catalog}} || ".manufacturing_analytics.fact_production_execution" || "
UNION ALL
  SELECT DISTINCT
    'plantProducesModel' AS rel,
    'Plant' AS subject_type,
    CAST(PLANT_KEY AS STRING) AS subject_key,
    'VehicleModel' AS object_type,
    CAST(MODEL_KEY AS STRING) AS object_key
  FROM " || {{catalog}} || ".manufacturing_analytics.fact_production_execution" || "
UNION ALL
  SELECT DISTINCT
    'supplierSuppliesPart' AS rel,
    'Supplier' AS subject_type,
    CAST(SUPPLIER_KEY AS STRING) AS subject_key,
    'Part' AS object_type,
    CAST(PART_KEY AS STRING) AS object_key
  FROM " || {{catalog}} || ".supply_chain_analytics.fact_supplier_quality" || "";
